auctions/urls.py
from django.urls import path

from . import views

app_name = 'auctions'

urlpatterns = [
    # listings
    path('', views.index, name="index"),
    path('categories/', views.get_categories, name='categories'),
    path('<slug:cat_slug>/',
        views.get_listings_by_category, name='listings'),
    path('<slug:cat_slug>/<slug:listing_slug>/',
        views.get_listing, name='listing'),
    # account
    path('register', views.register, name="register"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    # user actions
    path('add_listing', views.add_listing, name='add_listing'),
    path('watchlist', views.get_watchlist, name='get_watchlist'),
    path('<slug:cat_slug>/<slug:listing_slug>/add_to_watchlist',
        views.add_to_watchlist, name="watch"),
    path('<slug:cat_slug>/<slug:listing_slug>/close_listing',
        views.close_listing, name="close_listing"),
    path('my-listings', views.get_users_listings, name='get_users_listings'),
    path('bidding', views.get_bidding, name='bidding')
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator

from decimal import Decimal


class User(AbstractUser):
    phone_number = models.CharField(max_length=12)

class Category(models.Model):
    name = models.CharField(max_length=80)
    slug = models.SlugField(max_length=80, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('auctions:listings', args=[self.slug])

class Listing(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    start_bid = models.DecimalField(max_digits=1000000, decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))])
    image = models.URLField(blank=True)
    is_active = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('auctions:listing', kwargs={
            'cat_slug': self.category.slug, 'listing_slug': self.slug
        })

class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    bid = models.DecimalField(max_digits=19, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    # def __str__(self) -> str:
    #     return str(self.bid)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    text = models.TextField(max_length=3000)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    # is_active = models.BooleanField(default=True)

class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

auctions/forms.py
from django import forms
from django.db.models import Max
# from django.core.exceptions import ValidationError

from .models import User, Category, Listing, Bid, Comment

from decimal import Decimal


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = [
            'category', 'name',
            'image', 'start_bid',
            'description'
        ]
        labels = {
            'name': 'Listing name', 'category': 'Category',
            'description': 'Description', 'start_bid': 'Start bid',
            'image': 'Image URL'
        }

class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ('bid', 'listing')
        # exclude = ('listing',)
        labels = {'bid': 'Your Bid'}
        widgets = {'listing': forms.HiddenInput()}

    # def __init__(self, *args, **kwargs) -> None:
    #     # self.fields['listing'] = listing #self.data['listing']
    #     # super().__init__(self, *args, **kwargs)
    #     super(BidForm, self).__init__(*args, **kwargs)
    #     self.fields['listing'].widget = forms.HiddenInput()

    # def clean(self):
    #     cleaned_data = super().clean()
    #     new_bid = cleaned_data.get('bid')
    #     listing = cleaned_data.get('listing')
    #     # print(listing)
    #     start_bid = Listing.objects.get(name=listing)
    #     current_bid = Bid.objects.filter(listing=listing).aggregate(Max('bid'))
        
    #     if start_bid and current_bid >= new_bid:
    #         raise forms.ValidationError("Your bid must be higher than previous")

    def clean(self):
        new_bid = self.cleaned_data.get('bid')
        listing = self.cleaned_data.get('listing')
        start_bid = listing.start_bid
        bids = listing.bid_set.order_by('-date_added')
        current_bid = bids[0].bid if bids else start_bid

        if new_bid <= current_bid:
            raise forms.ValidationError(
                "Your bid must be higher than previous"
            )
        # return new_bid

    # def clean_bid(self):
    #     new_bid = self.cleaned_data['bid']
    #     start_bid = self.instance.listing.start_bid
    #     previous_bid = Bid.objects.filter(listing=self.instance.listing
    #         ).aggregate(Max('bid'))
    #     current_bid = previous_bid if previous_bid else start_bid
    #     if new_bid <= current_bid:
    #         raise forms.ValidationError(
    #             'Your bid must be higher than previous'
    #         )
    #     return new_bid

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Comment'}

auctions/views.py
from copy import copy
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify

from .models import User, Category, Listing, Bid, Comment, Watchlist
from .forms import ListingForm, BidForm, CommentForm


def index(request):
    newest_listings = Listing.objects.filter(is_active=True).order_by('-date_added')
    context = {'active_listings': newest_listings}
    return render(request, 'auctions/index.html', context)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


def get_categories(request):
    categories = Category.objects.order_by('name')
    return render(
        request, 'auctions/categories.html', {'categories': categories}
    )

def get_listings_by_category(request, cat_slug):
    category = get_object_or_404(Category, slug=cat_slug)
    listings = category.listing_set.filter(is_active=True).order_by('-date_added')
    context = {'category': category, 'listings': listings}
    return render(request, 'auctions/listings_by_cat.html', context)

def get_listing(request, cat_slug, listing_slug):
    listing = get_object_or_404(Listing, slug=listing_slug)
    # comments = listing.comment_set.order_by('-date_added')
    context = {
        'listing': listing, 'cat_slug': cat_slug,
        'listing_slug': listing_slug, 'start_bid': listing.start_bid,
        'listing_owner': listing.user
    }
    
    get_comments(listing, context)
    # make_a_bid(request, listing, context)
    # add_comment(request, listing, context)
    if request.user.is_authenticated:
        user_bids = listing.bid_set.order_by('-date_added')
        if user_bids:
            context['current_bid'] = user_bids[0].bid
            context['current_bid_owner'] = user_bids[0].user

        context['in_watchlist'] = User.objects.get(
            username=request.user).watchlist_set.filter(listing=listing)

        comment_form = CommentForm()
        context['comment_form'] = comment_form

        is_author = request.user == context['listing_owner']
        is_last_bidder = False
        if user_bids:
            is_last_bidder = user_bids[0] == request.user
        
        if not is_author and not is_last_bidder and listing.is_active: #request.user != listing.user:
            bid_form = BidForm()
            context['bid_form'] = bid_form
            # author = False
        if request.method == 'POST':
            post_data = copy(request.POST)
            post_data['listing'] = listing
            if 'bid_submit' in request.POST and not is_author:
                form = BidForm(data=post_data)
                # form.listing = listing
                # print(form)
                # filled = Decimal(form.data['bid'])
                # if filled <= listing.start_bid or filled <= context['current_bid']:
                #     raise ValidationError('Your bid must be higher than previous')
            elif 'comment_submit' in request.POST:
                form = CommentForm(data=post_data)

            if form.is_valid():
                form_data = form.save(commit=False)
                form_data.user = request.user
                form_data.listing = listing
                form_data.save()
                return redirect(listing.get_absolute_url())
            elif type(form) == BidForm:
                context['bid_form'] = form
            elif type(form) == CommentForm:
                context['comment_form'] = form
    return render(request, 'auctions/listing.html', context)

@login_required
def get_users_listings(request):
    user = get_object_or_404(User, username=request.user)
    users_listings = user.listing_set.order_by('-date_added')
    context = {'user': user, 'users_listings': users_listings}
    return render(request, 'auctions/users_listings.html', context)

@login_required
def get_bidding(request):
    user = get_object_or_404(User, username=request.user)
    bids = user.bid_set.order_by('-date_added')
    context = {'user': user, 'bids': bids}
    return render(request, 'auctions/bidding.html', context)

@login_required
def add_listing(request):
    if request.method != 'POST':
        listing_form = ListingForm()
    else:
        listing_form = ListingForm(data=request.POST)
        if listing_form.is_valid():
            listing = listing_form.save(commit=False)
            listing.user = request.user
            listing_id = Listing.objects.latest('date_added').id + 1 if Listing.objects.all() else 1
            listing.slug = slugify(f'{listing.name}_{listing_id}')
            listing.save()
            return redirect('auctions:listing', cat_slug=listing.category.slug, listing_slug=listing.slug)
            # return redirect('auctions:listings', request.POST.get('category'))
            
    context = {'listing_form': listing_form}
    return render(request, 'auctions/add_listing.html', context)

@login_required
def get_watchlist(request):
    watchlist = Watchlist.objects.filter(user=request.user).order_by('-date_added')
    context = {'watchlist': watchlist}
    return render(request, 'auctions/watchlist.html', context)

@login_required
def add_to_watchlist(request, cat_slug, listing_slug):
    listing = get_object_or_404(Listing, slug=listing_slug)
    if request.user != listing.user:
        watchlist, created = Watchlist.objects.get_or_create(user=request.user,
            listing=listing)
        if not created:
            watchlist.delete()
    return redirect('auctions:listing', cat_slug, listing_slug)

def get_comments(listing, listing_context):
    comments = listing.comment_set.order_by('-date_added')
    return listing_context.update({'comments': comments})

@login_required
def close_listing(request, cat_slug, listing_slug):
    listing = get_object_or_404(Listing, slug=listing_slug)
    listing.is_active = False
    listing.save()

    return redirect(listing.get_absolute_url())

# @login_required
# def make_a_bid(request, listing, listing_context):
#     if request.method != 'POST':
#         bid_form = BidForm()
#     elif request.method == 'POST' and 'bid' in request.POST:
#         bid_form = BidForm(data=request.POST)
#         if bid_form.is_valid():
#             new_bid = bid_form.save(commit=False)
#             new_bid.user = request.user
#             new_bid.listing = listing
#             new_bid.save()
#     context = {'bid_form': bid_form}
#     return listing_context.update(context)

# @login_required
# def add_comment(request, listing, listing_context):
#     if request.method != 'POST':
#         comment_form = CommentForm()
#     elif request.method == 'POST' and 'comment' in request.POST:
#         comment_form = CommentForm(data=request.POST)
#         if comment_form.is_valid():
#             new_comment = comment_form.save(commit=False)
#             new_comment.user = request.user
#             new_comment.listing = listing
#             new_comment.save()
#     context = {'comment_form': comment_form}
#     return listing_context.update(context)

auctions/templates/auctions/add_listing.html
{% extends 'auctions/layout.html' %}

{% block title %}Add listing{% endblock title %}

{% block body %}
    <h1 class="page-title">Add listing</h1>

    <div class="form-field">
        <form action="{% url 'auctions:add_listing' %}" method='POST'>
            {% csrf_token %}
            {% for field in listing_form %}
                <div class="field-form">
                    <div class="field-label">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    </div>
                    <div class="field">
                        {{ field }}
                    </div>
                    <div class="field-error">
                        {{ field.errors }}
                    </div>
                </div>
            {% endfor %}
            <div class="sbmt-btn">
                <button class="add-listing-btn" type="submit">Add Listing</button>
            </div>
        </form>
    </div>
{% endblock body %}

auctions/templates/auctions/bidding.html
{% extends 'auctions/layout.html' %}

{% block title %}Bidding{% endblock title %}

{% block body %}
    <h1 class="page-title">My bids</h1>

    {% if bids %}
        <div class="wlst">
            {% for bid in bids %}
                <a class="wlst-url" href="{{bid.listing.get_absolute_url}}">
                    <div class="wlst-img">
                        {% if bid.listing.image %}
                            <img class="wlst-img" src="{{ bid.listing.image }}" alt="{{ bid.listing.name }}">
                        {% else %}
                            <img class="wlst-img" src="https://media.istockphoto.com/vectors/default-image-icon-vector-missing-picture-page-for-website-design-or-vector-id1357365823?b=1&k=20&m=1357365823&s=170667a&w=0&h=y6ufWZhEt3vYWetga7F33Unbfta2oQXCZLUsEa67ydM=" alt="No image available">
                        {% endif %}
                    </div>
                    <div class="lst-name">
                        {{ bid.listing.name }}
                    </div>
                    <div class="lst-bid">
                        <small>Your bid:</small> US ${{ bid.bid }}
                    </div>
                </a>
            {% endfor %}
        </div>
    {% else %}
        There's nothing here yet.
    {% endif %}
{% endblock body %}

auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}

{% block title %}Categories{% endblock title %}

{% block body %}
    <h1 class="page-title">Categories</h1>
    {% if categories %}
        <ul class="basic-ul">
            {% for cat in categories %}
                <li><a class="basic-link" href="{{ cat.get_absolute_url }}">{{ cat }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Sorry, this page is empty.</p>
    {% endif %}
{% endblock body %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block title %}Active listings{% endblock title %}

{% block body %}
    <h1 class="page-title">Active Listings</h1>

    {% if active_listings %}
        <div class="active_listings">
            {% for listing in active_listings %}
                <a class="listing_mini" href="{{ listing.get_absolute_url }}">
                    <div class="lst-img">
                        {% if listing.image %}
                            <img class="limg" src="{{ listing.image }}" alt="{{ listing.name }}">
                        {% else %}
                            <img class="limg" src="https://media.istockphoto.com/vectors/default-image-icon-vector-missing-picture-page-for-website-design-or-vector-id1357365823?b=1&k=20&m=1357365823&s=170667a&w=0&h=y6ufWZhEt3vYWetga7F33Unbfta2oQXCZLUsEa67ydM=" alt="No image available">
                        {% endif %}
                    </div>
                    <div class="lst-name">
                        {{ listing.name }}
                    </div>
                    <div class="lst-bid">
                        US ${{ listing.start_bid }}
                    </div>
                    <div class="lst-descr">
                        <h4 class="h4-descr">Description</h4>
                        <p class="descr">
                            {{ listing.description }}
                        </p>
                    </div>
                </a>
            {% endfor %}
        </div>
    {% else %}
        Sorry, there's nothing here yet.
    {% endif %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock title %}</title>
        {% comment %} <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> {% endcomment %}
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="header">
            <ul class="nav">
                <li class="nav-item">
                    <div class="logo">
                        <a class="nav-link" href="{% url 'auctions:index' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-box-seam" viewBox="0 0 16 16">
                                <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5l2.404.961L10.404 2l-2.218-.887zm3.564 1.426L5.596 5 8 5.961 14.154 3.5l-2.404-.961zm3.25 1.7-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/>
                            </svg>
                            AUCTIONS
                        </a>
                    </div>
                </li>
                {% comment %} change to closed listings or something {% endcomment %}
                {% comment %} <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
                </li> {% endcomment %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:get_watchlist' %}">Watchlist</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:bidding' %}">Bidding</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:get_users_listings' %}">My listings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:add_listing' %}">Add listing</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="signed-in-info">
                {% if user.is_authenticated %}
                    <li class="signed-in-item">
                        Signed in as <strong>{{ user.username }}</strong>
                    </li>
                    <li class="signed-in-item">
                        <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="signed-in-item">
                        <a class="nav-link" href="{% url 'auctions:login' %}">Log in</a>
                    </li>
                    <li class="signed-in-item">
                        <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>

        <div class="body">
            {% block body %}{% endblock body %}
        </div>
        <div class="footer">
            <div>
                Copyright © 2021-2022 AUCTIONS Inc. All Rights Reserved. Joking :)
            </div>
        </div>
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends 'auctions/layout.html' %}

{% block title %}{{ listing.name }}{% endblock title %}

{% block body %}
    <div class="lst-grid">
        <div class="lg-img">
            {% if listing.image %}
                <img class="lg-img-big" src="{{ listing.image }}" alt="{{ listing.name }}">
            {% else %}
                <img class="lg-img-big" src="https://media.istockphoto.com/vectors/default-image-icon-vector-missing-picture-page-for-website-design-or-vector-id1357365823?b=1&k=20&m=1357365823&s=170667a&w=0&h=y6ufWZhEt3vYWetga7F33Unbfta2oQXCZLUsEa67ydM=" alt="No image available">
            {% endif %}
        </div>

        <div class="lg-name">
            <h1 class="lst-title">{{ listing.name }}</h1>
        </div>
        
        <div class="lg-actions">
            <div class="cur-bid">
                {% if current_bid %}
                    Current bid: <span id="price">US ${{ current_bid }}</span>
                {% else %}
                    Starting bid: <span id="price">US ${{ start_bid }}</span>
                {% endif %}
            </div>
    
            <div class="new-bid-info">
                {% if user.is_authenticated and user != listing_owner and user != current_bid_owner %}
                    {% if listing.is_active %}
                        <form id="id-bid-form" method="POST">
                            {% csrf_token %}
                            {% comment %} <input type="hidden" name="listing" value="{{ listing }}"> {% endcomment %}
                            {% comment %} {{ bid_form.listing.as_hidden }} {% endcomment %}
                            {{ bid_form.bid }}
                            {% comment %} {{ bid_form.errors }} {% endcomment %}
                            <button id="make-bid" type="submit" name="bid_submit" value="bid">Place bid</button>
                        </form>
                    {% endif %}
                {% elif user == current_bid_owner and listing.is_active %}
                    <h3>Your bid is the highest</h3>
                {% elif user == listing_owner and listing.is_active %}
                    <a id="gla-btn" href="{% url 'auctions:close_listing' cat_slug listing_slug %}">Close listing</a>
                {% endif %}
                {% if not listing.is_active and user == current_bid_owner %}
                    <h3>Your bid won!</h3>
                {% elif not listing.is_active and user != current_bid_owner %}
                    <h3>Winner: {{ current_bid_owner }}</h3>
                {% endif %}
            </div>

            {% if user.is_authenticated and user != listing_owner and listing.is_active %}
                <div class="watchlist">
                    <a id="gla-btn" href="{% url 'auctions:watch' cat_slug listing_slug %}">
                        {% if in_watchlist %}
                            Delete from watchlist
                        {% else %}
                            Add to watchlist
                        {% endif %}
                    </a>
                </div>
            {% endif %}
        </div>

        <div class="lg-seller">
            <span>
                Seller: {{ listing_owner }}
            </span>
        </div>
        <div class="lg-descr">
            <h3>Description</h3>
            {{ listing.description }}
        </div>
    </div>

    {% if user.is_authenticated %}
        <div class="lg-add-comment">
            <details>
                <summary>Add a comment</summary>
                <form class="comment-form" method="POST">
                    {% csrf_token %}
                    {{ comment_form.text }}
                    <div class="sbmt-btn">
                        <button id="comment" type="submit" name="comment_submit" value="comment">Comment</button>
                    </div>
                </form>
            </details>
        </div>
    {% endif %}
    
        <div class="lg-comments">
            <h3 id="comments-header">
                Comments: {{ comments.count }}
            </h3>
            {% if comments %}
                {% for comment in comments %}
                    <div class="comment">
                        <div class="comment-title">
                            by <b>{{ comment.user }}</b> <i>added {{ comment.date_added }}</i>
                        </div>
                        <div class="comment-text">
                            {{ comment.text }}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div style="border-bottom: solid 1px rgba(0,0,0,.1);">
                    <i>No comments for this listing yet.</i>
                </div>
            {% endif %}
        </div>
{% endblock body %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block title %}Log In{% endblock title %}

{% block body %}
    <div class="reg-log-card">
        <h1 class="page-title">Log In</h1>

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}
        
        <form action="{% url 'auctions:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <div class="field-label">
                    <label for="username">Username</label>
                </div>
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <div class="field-label">
                    <label for="username">Password</label>
                </div>
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <input class="reg-login-btn" type="submit" value="Log In">
        </form>
        <div class="acc-redirect">
            Don't have an account? <a href="{% url 'auctions:register' %}">Register here</a>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block title %}Register{% endblock title %}

{% block body %}
    <div class="reg-log-card">
        <h1 class="page-title">Register</h1>

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}
        <div class="reg-log-form">
            <form action="{% url 'auctions:register' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="field-label">
                        <label for="username">Username</label>
                    </div>
                    <input class="form-control" autofocus type="text" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <div class="field-label">
                        <label for="username">Email</label>
                    </div>
                    <input class="form-control" type="email" name="email" placeholder="Email Address">
                </div>
                <div class="form-group">
                    <div class="field-label">
                        <label for="username">Password</label>
                    </div>
                    <input class="form-control" type="password" name="password" placeholder="Password">
                </div>
                <div class="form-group">
                    <div class="field-label">
                        <label for="username">Confirm the password</label>
                    </div>
                    <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
                </div>
                <input class="reg-login-btn" type="submit" value="Register">
            </form>
            <div class="acc-redirect">
                Already have an account? <a href="{% url 'auctions:login' %}">Log In here</a>
            </div>
        </div>
    </div>
{% endblock %}